// jsallthefrontends/src/react/components/HelloWorld.jsx
import React from "react";
import Code from "./Code";

const HelloWorld = (props) => {
  const name = props.name || "World";

  return <div>Hello {name}!</div>;
};

const helloWorldCode = `const HelloWorld = (props) => {
  const name = props.name || "World";

  return <div>Hello {name}!</div>;
};
`;

export const HelloWorldCode = () => {
  return <Code code={helloWorldCode} language="javascript" />;
};

export default HelloWorld;

// vue/src/components/HelloWorld.vue
<template>
  <div id="hello-world">
    <h1>{{ msg }}</h1>
    <button @click="count++">count is: {{ count }}</button>
    <p>
      Edit <code>components/HelloWorld.vue</code> to test hot module
      replacement.
    </p>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  props: {
    msg: String,
  },
  data() {
    return {
      count: 0,
    };
  },
};
</script>
