// jsallthefrontends/src/react/components/Code.jsx
import React, { useEffect } from "react";
import Prism from "prismjs";
import "./Code.css";

const Code = ({ code, language }) => {
  useEffect(() => {
    Prism.highlightAll();
  }, []);

  return (
    <pre className="rounded-b-md lg:rounded-tl-none lg:rounded-bl-none lg:rounded-tr-md lg:rounded-br-md bg-gray-800 scrollbar-none m-0 p-4 text-base">
      <code className={`language-${language} inline-block scrolling-touch`}>
        {code}
      </code>
    </pre>
  );
};

export default Code;

// jsallthefrontends/src/svelte/components/Code.svelte
<script>
  import Prism from "prismjs";
  import { onMount } from "svelte";
  import "./Code.css";

  export let code = "";
  export let language = "javascript";

  onMount(async () => {
    Prism.highlightAll();
  });
</script>

<pre
  class="rounded-b-md lg:rounded-tl-none lg:rounded-bl-none lg:rounded-tr-md lg:rounded-br-md bg-gray-800 scrollbar-none m-0 p-4 text-base">
  <code
    class="language-{language} inline-block scrolling-touch">{code}</code>
</pre>
