// jsallthefrontends/src/vue/components/TabsCode.vue
<template>
  <Code :code="tabsCode" language="javascript" />
</template>

<script>
import Code from "./Code.vue";

export default {
  name: "TabsCode",
  components: {
    Code,
  },
  data() {
    return {
      tabsCode:
`<template>
  <div class="flex flex-col">
    <nav class="flex flex-row bg-white">
      <button
          class="text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none"
          type="button"
          v-for="tab in tabs"
          :key="tab"
          v-bind:class="{
            'text-blue-500 border-b-2 font-medium border-blue-500': activeTab === tab
          }"
          v-on:click="switchTab(tab)"
        >
          <slot :name="tabNavSlotName(tab)">{{ tab }}</slot>
      </button>
    </nav>
    <div class="p-6 bg-gray-100">
      <slot :name="tabContentSlotName"></slot>
    </div>
  </div>
</template>

<script>
export default {
  name: "Tabs",
  props: {
    initialActiveTab: {
      type: String,
      default: "",
    },
    tabs: {
      type: Array,
      default: [],
    },
  },
  data() {
    return {
      activeTab: this.initialActiveTab,
    };
  },
  methods: {
    tabNavSlotName(tabName) {
      return \`tab-nav-$\{tabName}\`;
    },

    selectTab(tabName) {
      this.activeTab = tabName;
    },
  },
  computed: {
    tabContentSlotName() {
      return \`tab-content-$\{this.activeTab}\`
    },
  },
};
<\/script>
`,
    };
  },
};
</script>

// jsallthefrontends/src/svelte/components/TabsCode.svelte
<script>
  import Code from "./Code.svelte";

  const tabsCode = `<script>
  // initialActiveTab looks like { tabName: "", tabNavComponent: TabNavComponent, tabContentComponent: TabContentComponent }
  export let initialActiveTab = {
    tabName: "",
    tabNavComponent: null,
    tabContentComponent: null,
  };
  // tabs structure looks like [{ tabName: "", tabNavComponent: TabNavComponent, tabContentComponent: TabContentComponent }, ...]
  export let tabs = [];

  let activeTab = initialActiveTab;

  const selectTab = (tab) => {
    activeTab = tab;
  };
<\/script>

<div class="flex flex-col">
  <nav class="flex flex-row bg-white">
    {#each tabs as tab, tabId (tabId)}
      <button
        class={activeTab.tabName === tab.tabName ? 'text-blue-500 border-b-2 font-medium border-blue-500 py-4 px-6 block hover:text-blue-500 focus:outline-none' : 'text-gray-600 py-4 px-6 block hover:text-blue-500 focus:outline-none'}
        type="button"
        on:click={selectTab(tab)}>
        <svelte:component this={tab.tabNavComponent} />
      </button>
    {/each}
  </nav>
  <div class="p-6 bg-gray-100">
    <svelte:component this={activeTab.tabContentComponent} />
  </div>
</div>`;
</script>

<Code code={tabsCode} language="javascript" />
