// jsallthefrontends/src/react/components/TabsPage.jsx
import React from "react";
import Layout from "./Layout";
import CodePreview from "./CodePreview";
import Tabs, { TabsCode } from "./Tabs";

const TabsPreview = () => {
  const tabs = [
    {
      tabName: "Tab 1",
      tabNavComponent: <>Tab 1</>,
      tabContentComponent: <>Tab 1 Content</>,
    },
    {
      tabName: "Tab 2",
      tabNavComponent: <>Tab 2</>,
      tabContentComponent: <>Tab 2 Content</>,
    },
    {
      tabName: "Tab 3",
      tabNavComponent: <>Tab 3</>,
      tabContentComponent: <>Tab 3 Content</>,
    },
  ];
  const initialActiveTab = tabs[0];

  return <Tabs initialActiveTab={initialActiveTab} tabs={tabs} />;
};

const TabsPage = () => {
  return (
    <Layout>
      <h2 className="mb-4">Tabs</h2>
      <p className="mb-6">
        Clicking a button and showing one piece of content at a time. Learn
        composition, conditionals, and state management with tabs.
      </p>
      <CodePreview preview={<TabsPreview />} code={<TabsCode />} />
    </Layout>
  );
};

export default TabsPage;

// jsallthefrontends/src/svelte/components/TabsPage.svelte
<script>
  import Layout from "./Layout.svelte";
  import CodePreview from "./CodePreview.svelte";
  import Tabs from "./Tabs.svelte";
  import TabsCode from "./TabsCode.svelte";
  import TabNav1 from "./TabNav1.svelte";
  import TabNav2 from "./TabNav2.svelte";
  import TabNav3 from "./TabNav3.svelte";
  import TabContent1 from "./TabContent1.svelte";
  import TabContent2 from "./TabContent2.svelte";
  import TabContent3 from "./TabContent3.svelte";

  const tabs = [
    {
      tabName: "Tab 1",
      tabNavComponent: TabNav1,
      tabContentComponent: TabContent1,
    },
    {
      tabName: "Tab 2",
      tabNavComponent: TabNav2,
      tabContentComponent: TabContent2,
    },
    {
      tabName: "Tab 3",
      tabNavComponent: TabNav3,
      tabContentComponent: TabContent3,
    },
  ];

  const initialActiveTab = tabs[0];
</script>

<Layout>
  <h2 class="mb-4">Tabs</h2>
  <p class="mb-6">
    Clicking a button and showing one piece of content at a time. Learn
    composition, conditionals, and state management with tabs.
  </p>
  <CodePreview>
    <div slot="preview">
      <Tabs {initialActiveTab} {tabs} />
    </div>
    <div slot="code">
      <TabsCode />
    </div>
  </CodePreview>
</Layout>
