// jsallthefrontends/src/vue/components/HelloWorldPage.vue
<template>
  <Layout>
    <template v-slot:children>
      <h2 class="mb-4">Hello World</h2>
      <p class="mb-6">
        The tried and true baby steps into a new world. Greetings from your
        first React component!
      </p>
      <CodePreview>
        <template v-slot:preview>
          <HelloWorld />
          <HelloWorld name="Alfred" />
        </template>
        <template v-slot:code>
          <HelloWorldCode />
        </template>
      </CodePreview>
    </template>
  </Layout>
</template>

<script>
import Layout from "./Layout.vue";
import CodePreview from "./CodePreview.vue";
import HelloWorld from "./HelloWorld.vue";
import HelloWorldCode from "./HelloWorldCode.vue";

export default {
  name: "HelloWorldPage",
  components: {
    HelloWorld,
    HelloWorldCode,
    CodePreview,
    Layout,
  },
};
</script>

// jsallthefrontends/src/react/components/HelloWorldPage.jsx
import React from "react";
import Layout from "./Layout";
import CodePreview from "./CodePreview";
import HelloWorld, { HelloWorldCode } from "./HelloWorld";

const HelloWorldPreview = () => {
  return (
    <>
      <HelloWorld />
      <HelloWorld name="Alfred" />
    </>
  );
};

const HelloWorldPage = () => {
  return (
    <Layout>
      <h2 className="mb-4">Hello World</h2>
      <p className="mb-6">
        The tried and true baby steps into a new world. Greetings from your
        first React component!
      </p>
      <CodePreview preview={<HelloWorldPreview />} code={<HelloWorldCode />} />
    </Layout>
  );
};

export default HelloWorldPage;
