// jsallthefrontends/src/vue/components/HomePage.vue
<template>
  <Layout>
    <template v-slot:children>
      <h2 class="mb-2">Vue Code Examples</h2>
      <p class="mb-6">
        Sometimes you want a quick peek of what it is like to implement
        something in another frontend framework. Let's dive into Vue 2 code
        examples! You can even open up the Vue dev tools if you have it
        installed in your browser to view the components.
      </p>
      <CodePreviewCard
        title="Hello World"
        description="The tried and true baby steps into a new world. Greetings from your first Vue component!"
        previewLink="/hello-world"
        v-bind:otherFrontendsAvailable="['react', 'svelte']"
      />
    </template>
  </Layout>
</template>

<script>
import Layout from "./Layout.vue";
import CodePreviewCard from "./CodePreviewCard.vue";

export default {
  name: "HomePage",
  components: {
    Layout,
    CodePreviewCard,
  },
};
</script>

// jsallthefrontends/src/react/components/HomePage.jsx
import React from "react";
import Layout from "./Layout";
import CodePreviewCard from "./CodePreviewCard";

const HomePage = () => {
  return (
    <Layout>
      <h2 className="mb-2">React Code Examples</h2>
      <p className="mb-6">
        Sometimes you want a quick peek of what it is like to implement
        something in another frontend framework. Let's dive into React 16 code
        examples! You can even open up the React dev tools if you have it
        installed in your browser to view the components.
      </p>
      <CodePreviewCard
        title="Hello World"
        description="The tried and true baby steps into a new world. Greetings from your
        first React component!"
        previewLink="/hello-world"
        otherFrontendsAvailable={["vue", "svelte"]}
      />
    </Layout>
  );
};

export default HomePage;
