// jsallthefrontends/src/vue/components/TabsPage.vue
<template>
  <Layout>
    <template v-slot:children>
      <h2 class="mb-4">Tabs</h2>
      <p class="mb-6">
        Clicking a button and showing one piece of content at a time. Learn composition, conditionals, and state management with tabs.
      </p>
      <CodePreview>
        <template v-slot:preview>
          <Tabs :tabs="tabs" :initialActiveTab="initialActiveTab">
            <template slot="tab-nav-tab1">
              Tab 1
            </template>
            <template slot="tab-content-tab1">
              Tab 1 Content
            </template>
            <template slot="tab-nav-tab2">
              Tab 2
            </template>
            <template slot="tab-content-tab2">
              Tab 2 Content
            </template>
            <template slot="tab-nav-tab3">
              Tab 3
            </template>
            <template slot="tab-content-tab3">
              Tab 3 Content
            </template>
          </Tabs>
        </template>
        <template v-slot:code>
          <TabsCode />
        </template>
      </CodePreview>
    </template>
  </Layout>
</template>

<script>
import Layout from "./Layout.vue";
import CodePreview from "./CodePreview.vue";
import Tabs from "./Tabs.vue";
import TabsCode from "./TabsCode.vue";

export default {
  name: "TabsPage",
  components: {
    Layout,
    CodePreview,
    Tabs,
    TabsCode,
  },
  data() {
    return {
      initialActiveTab: "tab1",
      tabs: ["tab1", "tab2", "tab3"],
    };
  },
};
</script>

// jsallthefrontends/src/react/components/TabsPage.jsx
import React from "react";
import Layout from "./Layout";
import CodePreview from "./CodePreview";
import Tabs, { TabsCode } from "./Tabs";

const TabsPreview = () => {
  const tabs = [
    {
      tabName: "Tab 1",
      tabNavComponent: <>Tab 1</>,
      tabContentComponent: <>Tab 1 Content</>,
    },
    {
      tabName: "Tab 2",
      tabNavComponent: <>Tab 2</>,
      tabContentComponent: <>Tab 2 Content</>,
    },
    {
      tabName: "Tab 3",
      tabNavComponent: <>Tab 3</>,
      tabContentComponent: <>Tab 3 Content</>,
    },
  ];
  const initialActiveTab = tabs[0];

  return <Tabs initialActiveTab={initialActiveTab} tabs={tabs} />;
};

const TabsPage = () => {
  return (
    <Layout>
      <h2 className="mb-4">Tabs</h2>
      <p className="mb-6">
        Clicking a button and showing one piece of content at a time. Learn
        composition, conditionals, and state management with tabs.
      </p>
      <CodePreview preview={<TabsPreview />} code={<TabsCode />} />
    </Layout>
  );
};

export default TabsPage;
