// jsallthefrontends/src/svelte/App.svelte
<script>
  import HelloWorld from "./components/HelloWorld.svelte";
  import HelloWorldCode from "./components/HelloWorldCode.svelte";
  import "./App.css";
  console.log("over here in svelte!");
</script>

<style>
</style>

<div>
  <h1>Hello from a Svelte file hahahss</h1>
  <HelloWorld />
  <HelloWorld name="Alfred" />
  <HelloWorldCode />
</div>

// jsallthefrontends/src/vue/App.vue
<style>
@import "./App.css";
</style>

<template>
  <div>
    <h1>Hello from Vue!!</h1>
    <HelloWorld />
    <HelloWorld name="Alfred" />
    <HelloWorldCode />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";
import HelloWorldCode from "./components/HelloWorldCode.vue";

export default {
  name: "App",
  components: {
    HelloWorld,
    HelloWorldCode,
  },
};
</script>
